import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";

const inter = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Analytics Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
   <div className="flex h-screen w-full bg-[#fafafa]">
      <div className="hidden md:block">
      <Sidebar />
      </div>
     <main className="flex flex-col w-full md:ml-24">
     {children}
     </main>
   </div>
        </body>
    </html>
  );
}
