import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { Providers } from "./providers";

const inter = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Analytics Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers
        attribute="class"
        defaultTheme="light"
        enableSystem={false}
        disableTransitionOnChange
        >
   <div className="flex h-screen w-full bg-[#fafafa] dark:bg-[#111827]">
      <div className="hidden md:block">
      <Sidebar />
      </div>
     <main className="flex flex-col w-full md:ml-24">
     {children}
     </main>
   </div>
   </Providers>
        </body>
    </html>
  );
}
